[font]
    # normal = { family = "FiraCode Nerd Font", style = "Regular" }
    # normal = { family = "DaddyTimeMono Nerd Font", style = "Regular" }
    normal = { family = "RecMonoLinear Nerd Font", style = "Regular" }
    # normal = { family = "Terminess Nerd Font", style = "Regular" }
    # normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
    # normal = { family = "ZedMono Nerd Font", style = "Regular" }
    # normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
    # normal = { family = "IosevkaTermSlab Nerd Font", style = "Regular" }
    # Also, see Rn, Ar, Kr, Ne, Xe
    # normal = { family = "MonaspiceAr Nerd Font", style = "Regular" }
    # normal = { family = "MonaspiceXe Nerd Font", style = "Regular" }

    size = 14.0

[general]
import = [
    # default
    "~/.config/alacritty/base-colors.toml",
    "~/.config/alacritty/wallust.toml"
]

[window]
    padding = {x = 10, y = 10}
    # opacity = 0.8
    decorations = "None"

[terminal]
    shell = "/bin/zsh"

[keyboard]
    bindings = [
        {key = "Return", mods = "Super|Shift", command = "alacritty"},
        {key = "Escape", mods = "Alt", mode = "~vi | ~AppKeypad", action = "ToggleViMode"},

        {key = "w", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001BF"},
        {key = "b", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001BB"},
        {key = "k", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001B[A"},
        {key = "j", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001B[B"},
        {key = "l", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001B[C"},
        {key = "h", mods = "Alt", mode = "~vi | ~AppKeypad", chars = "\u001B[D"},
    ]

[cursor]
    vi_mode_style = { shape="Block", blinking="Off" }
