include colors-default.conf
include colors-wallust.conf

font_family      RecMonoLinear Nerd Font
bold_font        RecMonoLinear Nerd Font Bold
italic_font      RecMonoLinear Nerd Font Italic
bold_italic_font RecMonoLinear Nerd Font Bold Italic

font_size 14.0

map ctrl+=  increase_font_size
map ctrl+minus decrease_font_size
map ctrl+0     restore_font_size

# Transparency
background_opacity 0.90
enable_background_opacity yes

# Disable audio
enable_audio_bell no
visual_bell_duration 0
bell_path none

confirm_os_window_close 0
