#!/bin/sh

# power aliases
alias poweroff='loginctl poweroff'
alias reboot='loginctl reboot'

# ls aliases
alias ls='ls -h --si --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias lt='ls -ltr'
alias l='ls -CF'
alias lsgr="git ls-files -coz --exclude-standard | xargs -0 stat --format '%y %n' | sort | awk '{print \$1, substr(\$2,1,8), \$4}'"

alias vi='nvim'

alias cdf='cd $(ls | fzf)'

# cp recents
alias cpd='cp ~/dl/$(ls -t ~/dl | head -n 1)'
alias cps='cp ~/pix/screenshots/$(ls -t ~/pix/screenshots/ | head -n 1)'

alias free='free -h'

alias o='xdg-open'

alias gpt='(cd ~/dl/llama.cpp/build/bin && ./llama-cli -m ~/.local/share/nomic.ai/GPT4All/gpt4all-falcon-newbpe-q4_0.gguf -ngl 99)'

# use rg if available, either way, use color
[ command -v rg >/dev/null 2>&1 ] && alias grep='rg --color=auto' || alias grep='grep --color=auto'

# git aliases
alias gs='git status'
alias gd='git diff'
alias gsw='git switch'
alias gsu='git submodule update'
alias glog='git log --oneline --graph'
alias gsun='git submodule foreach --quiet '\''if [ -n "$sha1" ] && [ "$(git rev-parse HEAD)" != "$sha1" ]; then echo -e "\033[36m$name\033[0m"; git log --oneline $sha1..HEAD; fi'\'''
# use personal git credentials
alias egit='GIT_CONFIG_GLOBAL=$XDG_CONFIG_HOME/git/personal_config git'

# copy paste
alias xc="xclip -sel clip <"
alias xp="xclip -sel clip -o >"

# gio controls
alias tsh="gio trash"

# some nice utils
alias lst='ls -t | head -n1'
alias logcat='cat "$(lst)"'
alias nvimr='nvim "$(lst)"'

alias cmake-dep='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..'

# youtube audio downloader, -x is audio only
alias yta='yt-dlp --add-metadata -xic --audio-format mp3'

# minicom alias for ACM0
alias acm0='minicom -b 115200 -o -D /dev/ttyACM0'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# python .venv auto-sourcing
cd() {
  builtin cd "$@"

  if [[ -z "$VIRTUAL_ENV" ]] ; then
      # If env folder is found then activate the vitualenv
      if [[ -d ./.venv ]] ; then
        . ./.venv/bin/activate
      fi
  else
      # check the current folder belong to earlier VIRTUAL_ENV folder
      # if yes then do nothing else deactivate
      parentdir="$(dirname "$VIRTUAL_ENV")"
      if [[ "$PWD"/ != "$parentdir"/* ]] ; then
        deactivate
      fi
  fi
}

