theme[main_bg]="{{ background }}"
theme[main_fg]="{{ foreground }}"
theme[title]="{{ foreground }}"
theme[hi_fg]="{{ color4 }}"
theme[selected_bg]="{{ color0 }}"
theme[selected_fg]="{{ color4 }}"
theme[inactive_fg]="{{ color8 }}"
theme[graph_text]="{{ color7 }}"
theme[meter_bg]="{{ color0 }}"
theme[proc_misc]="{{ color7 }}"

theme[cpu_box]="{{ color6 }}"
theme[mem_box]="{{ color2 }}"
theme[net_box]="{{ color5 }}"
theme[proc_box]="{{ color1 }}"
theme[div_line]="{{ color8 }}"

theme[temp_start]="{{ color3 }}"
theme[temp_mid]="{{ color3 }}"
theme[temp_end]="{{ color1 }}"

theme[cpu_start]="{{ color6 }}"
theme[cpu_mid]="{{ color4 }}"
theme[cpu_end]="{{ color2 }}"

theme[free_start]="{{ color2 }}"
theme[free_mid]="{{ color2 }}"
theme[free_end]="{{ color10 }}"

theme[cached_start]="{{ color5 }}"
theme[cached_mid]="{{ color5 }}"
theme[cached_end]="{{ color13 }}"

theme[available_start]="{{ color7 }}"
theme[available_mid]="{{ color1 }}"
theme[available_end]="{{ color1 }}"

theme[used_start]="{{ color3 }}"
theme[used_mid]="{{ color3 }}"
theme[used_end]="{{ color1 }}"

theme[download_start]="{{ color4 }}"
theme[download_mid]="{{ color4 }}"
theme[download_end]="{{ color5 }}"

theme[upload_start]="{{ color4 }}"
theme[upload_mid]="{{ color4 }}"
theme[upload_end]="{{ color5 }}"

theme[process_start]="{{ color6 }}"
theme[process_mid]="{{ color4 }}"
theme[process_end]="{{ color2 }}"
