-- auto-generated by wallust

local M = {}

M.bg = "{{ background }}"
M.fg = "{{ foreground }}"

M.black   = "{{ color0 }}"
M.red     = "{{ color1 }}"
M.green   = "{{ color2 }}"
M.yellow  = "{{ color3 }}"
M.blue    = "{{ color4 }}"
M.magenta = "{{ color5 }}"
M.cyan    = "{{ color6 }}"
M.white   = "{{ color7 }}"

M.bright_black   = "{{ color8 }}"
M.bright_red     = "{{ color9 }}"
M.bright_green   = "{{ color10 }}"
M.bright_yellow  = "{{ color11 }}"
M.bright_blue    = "{{ color12 }}"
M.bright_magenta = "{{ color13 }}"
M.bright_cyan    = "{{ color14 }}"
M.bright_white   = "{{ color15 }}"

return M
