#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Open a temporary file with Vim. Once Vim is closed, copy the contents of that
# file to the system clipboard.

###
# defs
###

AW_PATH=$HOME/.vim-anywhere
TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")
# # Capture the current clipboard contents and store it in TMPFILE
# xclip -selection primary -o > "$TMPFILE"

# Check if there is currently any selected (highlighted) text in the primary selection
if xclip -selection primary -o > /dev/null 2>&1; then
    # If there is selected text, capture it into the temporary file
    xclip -selection primary -o > "$TMPFILE"
else
    touch $TMPFILE
fi

err() { echo -e "$@" 1>&2; }

require_file_exists() {
  if [ ! -e $1 ]; then
    err "$1 does not exist. ${@:2}"
    exit 1
  fi
}

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# run
###

# AW_PATH=$HOME/.vim-anywhere
# TMPFILE_DIR=/tmp/vim-anywhere
# TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")

# mkdir -p $TMPFILE_DIR
# touch $TMPFILE


# Linux
if [[ $OSTYPE == "linux-gnu" ]]; then
  chmod o-r $TMPFILE # Make file only readable by you
  nvim $TMPFILE
  
  cat $TMPFILE | nohup xclip -selection clipboard
fi
