pragma Singleton
import QtQuick
import Quickshell

// Single shared style singleton for the whole shell (bar, keytree,
// imagepicker). The "wallust palette" block below is the only part
// regenerated by wallust, from the sibling modules/common/theme.qml.template
// on every `wallust run` - everything past it is a plain QML binding
// computed from that block, so widgets never touch raw palette colors and
// stay in sync automatically. That template is copied by hand to wherever
// the live wallust config's templates dir is - if you edit this file's
// semantic section, mirror the edit in the template too or it's silently
// dropped on the next regen.
Singleton {
    id: root

    // ---- Wallust palette (regenerated - see modules/common/theme.qml.template) ----
    readonly property color background: "#020308"
    readonly property color foreground: "#BCD5FF"
    readonly property color cursor: "#92B3DF"

    readonly property color color0: "#03060C"
    readonly property color color1: "#434F57"
    readonly property color color2: "#404E5A"
    readonly property color color3: "#455360"
    readonly property color color4: "#657E9A"
    readonly property color color5: "#5F7B9B"
    readonly property color color6: "#657797"
    readonly property color color7: "#AFC7F5"
    readonly property color color8: "#6C84AD"
    readonly property color color9: "#465560"
    readonly property color color10: "#415465"
    readonly property color color11: "#495C6C"
    readonly property color color12: "#5882AF"
    readonly property color color13: "#6892C0"
    readonly property color color14: "#879FCA"
    readonly property color color15: "#CEDBF1"

    // ---- Static settings (not wallust-managed) ----
    readonly property string fontFamily: "FiraCode Nerd Font"
    readonly property int fontSize: 14
    readonly property int barHeight: 32

    // ---- Semantic colors, derived from the palette above ----

    // Generic text - deliberately plain white rather than the wallust
    // foreground (which trends pale/tinted on muted palettes and reads worse
    // at small bar font sizes than true white does); color variety instead
    // lives in accents/glyphs/separator, not body text.
    readonly property color text: "#ffffff"
    readonly property color dimText: root.color8

    // Text colour for content drawn on top of an accent-filled badge (e.g.
    // the focused/urgent workspace chip text, the "today" cell in the
    // calendar popup) - tracks color0, distinct from the wallust
    // `background` special above even though they're the same value here.
    readonly property color onAccentText: root.color0

    // The single most saturated color in the palette - wallust's muted/pastel
    // palettes otherwise leave every color close to grayscale, so this is
    // the only one that reliably reads as "distinct" against them. Used for
    // the one primary highlight per widget (focused workspace, now-playing
    // indicator, calendar's "today", ImagePicker's selection ring) - NOT for
    // secondary/tertiary states, which stay on their own duller colors.
    readonly property color accent: root.color13

    // Bar workspaces
    readonly property color focusedWorkspace: root.accent
    readonly property color activeWorkspace: root.color5
    readonly property color inactiveWorkspace: root.color4
    readonly property color urgentWorkspace: root.color1

    // Pills (bar widget group containers) and popup/overlay chrome
    // (Calendar/Music/Stator previews, ImagePicker) - deliberately opaque-ish
    // rather than barely-there so they read clearly over any wallpaper.
    readonly property color pillBg: withAlpha(root.color0, 0.85)
    readonly property color pillBorder: withAlpha(root.foreground, 0.2)

    // Generic hover highlight (e.g. ImagePicker grid tiles)
    readonly property color hoverBg: withAlpha(root.foreground, 0.1)

    // Separator glyph between pill widgets
    readonly property color separator: root.color8

    // Keytree - executable (leaf) nodes
    readonly property color leafBg: withAlpha(root.color0, 0.8)
    readonly property color leafBorder: root.color12

    // Keytree - group/subtree nodes (slightly lighter bg than leaves, and a
    // neutral border, so the two node kinds stay visually distinct)
    readonly property color groupBg: withAlpha(lighten(root.color0, 0.08), 0.8)
    readonly property color groupBorder: root.color7

    // Keytree - text
    readonly property color keyText: root.color8
    readonly property color labelText: root.color15

    // Keytree - connectors
    readonly property color connector: root.color8
    readonly property color centerDot: root.color7

    // Keytree - search panel
    readonly property color searchBg: root.pillBg
    readonly property color searchBorder: root.color7
    readonly property color searchSelection: withAlpha(root.color7, 0.8)
    readonly property color searchText: root.color15

    function withAlpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a);
    }
    function lighten(c, amount) {
        return Qt.rgba(Math.min(c.r + amount, 1), Math.min(c.g + amount, 1), Math.min(c.b + amount, 1), c.a);
    }
}
