#!/bin/sh

STORE_PATH="$XDG_DATA_HOME/password-store"

password_files=$(find "$STORE_PATH" -type f -name "*.gpg")

STRIP_PREFIX="s|^$STORE_PATH/||"
STRIP_SUFFIX="s|\.gpg$||"

password_entry=$(echo "$password_files" | \
    sed "$STRIP_PREFIX" | \
    sed "$STRIP_SUFFIX" | \
    rofi -dmenu -p "Select a password")

[ -n "$password_entry" ] && pass show "$password_entry" | head -n1 | xclip -selection clipboard
