#!/bin/python

import os
import sys
from datetime import date, timedelta

bday = date(2003, 8, 19)

notes_path = f"{os.path.expanduser('~')}/vault/Daily"
template = f"{notes_path}/_daily_template.md"
today = date.today()
if (len(sys.argv) != 1):
    today += timedelta(days=int(sys.argv[1]))
outfile = f"{notes_path}/{today.isoformat()}.md"

if not os.path.isfile(outfile):
    years = today.year - bday.year
    if (today.month, today.day) < (bday.month, bday.day):
        years -= 1
    bible_plan_path = f"{notes_path}/bible_plan_{years}.csv"

    start_year = today.year
    if (today.month, today.day) < (bday.month, bday.day):
        start_year -= 1
    start_date = bday.replace(year=start_year)
    today_entry = (today - start_date).days

    with open(bible_plan_path, "r") as f:
        bible_plan_lines = f.readlines()
        weeks = int(today_entry / 7)
        dow = today_entry % 7
        entry_i = 9 * weeks + 1 + dow
        today_passage = bible_plan_lines[entry_i]

        passages = []
        def split_ref(ref: str):
            import re
            match = re.match(r"(\d?\s*[A-Za-z]+)\s+(\d+(?:-\d+)?)", ref)
            if not match:
                raise ValueError("No regex match found!")
            book, chapters = match.groups()
            return book.strip(), chapters

        for entry in [x.strip() for x in today_passage.split(",")]:
            book, chaps = split_ref(entry)
            passages.append(f"{book} {chaps}")

    with open(template, "r") as fin, open(outfile, "w") as fout:
        for i, line in enumerate(fin):
            if line.startswith("created:"):
                fout.write(f"created: {today.isoformat()}\n")
                continue
            fout.write(line)
            if line.startswith("passages:"):
                for p in passages:
                    fout.write(f" - {p}\n")

print(outfile)
