#!/bin/sh

###
# defs
###

TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S.txt")

## Check if the directory exists
if [ ! -d "$TMPFILE_DIR" ]; then
  mkdir -p "$TMPFILE_DIR"
fi

# Check if there is currently any selected (highlighted) text in the primary selection
if xclip -selection primary -o > /dev/null 2>&1; then
    # If there is selected text, capture it into the temporary file
    xclip -selection primary -o > "$TMPFILE"
else
    touch $TMPFILE
fi

err() { echo -e "$@" 1>&2; }

require_file_exists() {
  if [ ! -e $1 ]; then
    err "$1 does not exist. ${@:2}"
    exit 1
  fi
}

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# run
###

chmod o-r $TMPFILE # Make file only readable by you
nvim $TMPFILE

nohup xclip -selection clipboard < "$TMPFILE" >/dev/null 2>&1 &
