#!/bin/sh

[ -z "$WAYLAND_DISPLAY" ] && [ "$DISPLAY" ] || exit 0

PRIMARY="DisplayPort-1"
SECONDARY="DisplayPort-0"
SOLO="HDMI-A-0"

STATE_FILE="/tmp/monitor_toggle_state"

if [ "$1" = "--phone"  ]; then
    xrandr --output "$PRIMARY" --auto --primary --scale 0.5x0.5 \
        --output "$SECONDARY" --off \
        --output "$SOLO" --off
    wallpaper-picker --stop > /dev/null 2>&1
    rm "$STATE_FILE"
    exit 1
fi

if [ ! -f "$STATE_FILE" ] || [ "$1" = "--reset" ]; then
    state="reset"
else
    state=$(cat "$STATE_FILE")
fi

if [ "$state" = "reset" ] || [ "$state" = "solo" ]; then
    xrandr --output "$PRIMARY" --auto --primary \
        --output "$SECONDARY" --auto --rotate right --left-of "$PRIMARY" \
        --output "$SOLO" --off
    wallpaper-picker > /dev/null 2>&1
    echo "dual" > "$STATE_FILE"
else
    xrandr --output "$PRIMARY" --off \
        --output "$SECONDARY" --off \
        --output "$SOLO" --auto
    wallpaper-picker --stop > /dev/null 2>&1
    echo "solo" > "$STATE_FILE"
fi
