#!/bin/bash

STORE_PATH="$HOME/.password-store"

PASSWORD_FILES=$(find "$STORE_PATH" -type f -name "*.gpg")

STRIP_PREFIX="s|^$STORE_PATH/||"
STRIP_SUFFIX="s|\.gpg$||"

PASSWORD_ENTRY=$(echo "$PASSWORD_FILES" | \
    sed "$STRIP_PREFIX" | \
    sed "$STRIP_SUFFIX" | \
    rofi -dmenu -p "Select a password")

[ -n "$PASSWORD_ENTRY" ] && pass show "$PASSWORD_ENTRY" | head -n1 | xclip -selection clipboard
