idle_bg = "#060300"
idle_fg = "#d2d4de"

info_bg = "#090501"
info_fg = "#d2d4de"

good_bg = "#43414F"
good_fg = "#d2d4de"

warning_bg = "#45485A"
warning_fg = "#d2d4de"

critical_bg = "#4D505A"
critical_fg = "#d2d4de"

separator = " "
separator_fg = "auto"
separator_bg = "auto"

alternating_tint_bg = "#544B60"
